import type { Agency } from '@/lib/campaignTypes'

/**
 * 목업 대행사 8건 — 정산·세금계산서 발행·대금 지급 요청서 테스트용.
 * 실제 사업자등록번호는 임의 생성값. 운영 배포 전 반드시 실제 데이터로 교체.
 */
export function generateMockAgencies(): Agency[] {
  const now = new Date().toISOString()
  return [
    {
      id: 'mock-ag-ust',
      name: '㈜유에스티',
      contactName: '송민호',
      email: 'minho@ust.co',
      phone: '02-1234-5678',
      corporateName: '주식회사 유에스티',
      businessNumber: '124-87-20754',
      representative: '방민규',
      address: '경기도 화성시 동탄산단2길 50(방교동) ㈜유에스티 본사',
      businessType: '제조업',
      businessItem: '화장품',
      defaultMarkupRate: 10,
      paymentDueDays: 30,
      paymentBasis: '월말 마감 익월 30일',
      bankName: '기업은행',
      bankAccountNumber: '123-456789-01-018',
      bankAccountHolder: '주식회사 유에스티',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-peterpan',
      name: '㈜피터팬랩',
      contactName: '이정원',
      email: 'jw.lee@peterpan.co.kr',
      phone: '02-555-1234',
      corporateName: '주식회사 피터팬랩',
      businessNumber: '212-87-44512',
      representative: '김수정',
      address: '서울특별시 강남구 테헤란로 152 강남파이낸스센터 12층',
      businessType: '서비스업',
      businessItem: '광고대행, 미디어',
      defaultMarkupRate: 10,
      paymentDueDays: 30,
      paymentBasis: '월말 마감 익월 30일',
      bankName: '기업은행',
      bankAccountNumber: '537-033910-01-017',
      bankAccountHolder: '(주)피터팬랩',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-mediasol',
      name: '㈜미디어솔루션',
      contactName: '박지연',
      email: 'jy.park@mediasol.co.kr',
      phone: '02-3456-7890',
      corporateName: '주식회사 미디어솔루션',
      businessNumber: '356-81-22398',
      representative: '박지영',
      address: '서울특별시 마포구 월드컵북로 396 누리꿈스퀘어 비즈니스타워 8층',
      businessType: '서비스업',
      businessItem: '온라인 광고',
      defaultMarkupRate: 12,
      paymentDueDays: 45,
      paymentBasis: '월말 마감 익월 45일',
      bankName: '신한은행',
      bankAccountNumber: '110-456-789012',
      bankAccountHolder: '주식회사 미디어솔루션',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-adgroup',
      name: '㈜애드그룹',
      contactName: '최영수',
      email: 'ys.choi@adgroup.kr',
      phone: '02-2222-3333',
      corporateName: '주식회사 애드그룹',
      businessNumber: '107-86-55812',
      representative: '최영수',
      address: '서울특별시 송파구 올림픽로 300 롯데월드타워 23층',
      businessType: '서비스업',
      businessItem: '광고대행',
      defaultMarkupRate: 8,
      paymentDueDays: 60,
      paymentBasis: '월말 마감 익월 60일',
      bankName: '국민은행',
      bankAccountNumber: '904502-04-128876',
      bankAccountHolder: '주식회사 애드그룹',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-bigbang',
      name: '㈜빅뱅애드',
      contactName: '김혜진',
      email: 'hj.kim@bigbangad.com',
      phone: '02-789-1010',
      corporateName: '주식회사 빅뱅애드',
      businessNumber: '230-87-91244',
      representative: '김혜진',
      address: '서울특별시 강남구 강남대로 542 영풍빌딩 5층',
      businessType: '서비스업',
      businessItem: '온라인 광고, 디지털 마케팅',
      defaultMarkupRate: 10,
      paymentDueDays: 30,
      paymentBasis: '선입금',
      bankName: '하나은행',
      bankAccountNumber: '157-910021-04207',
      bankAccountHolder: '(주)빅뱅애드',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-trinity',
      name: '㈜트리니티미디어',
      contactName: '윤성호',
      email: 'sh.yoon@trinity.kr',
      phone: '02-4567-8910',
      corporateName: '주식회사 트리니티미디어',
      businessNumber: '142-81-67234',
      representative: '윤성호',
      address: '서울특별시 영등포구 여의대로 24 전경련회관 31층',
      businessType: '서비스업',
      businessItem: 'CTV/OTT 광고',
      defaultMarkupRate: 11,
      paymentDueDays: 45,
      paymentBasis: '월말 마감 익월 45일',
      bankName: '우리은행',
      bankAccountNumber: '1005-602-345678',
      bankAccountHolder: '주식회사 트리니티미디어',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-spark',
      name: '㈜스파크커뮤니케이션',
      contactName: '정나영',
      email: 'ny.jung@spark.co.kr',
      phone: '031-123-4567',
      corporateName: '주식회사 스파크커뮤니케이션',
      businessNumber: '418-87-23761',
      representative: '정나영',
      address: '경기도 성남시 분당구 판교역로 235 알파돔타워 12층',
      businessType: '서비스업',
      businessItem: '광고기획, 미디어렙',
      defaultMarkupRate: 9,
      paymentDueDays: 30,
      paymentBasis: '월말 마감 익월 30일',
      bankName: '농협은행',
      bankAccountNumber: '301-0123-4567-21',
      bankAccountHolder: '(주)스파크커뮤니케이션',
      createdAt: now, updatedAt: now,
    },
    {
      id: 'mock-ag-vision',
      name: '㈜비전미디어',
      contactName: '한지훈',
      email: 'jh.han@visionmedia.kr',
      phone: '02-9999-0000',
      corporateName: '주식회사 비전미디어',
      businessNumber: '129-81-88912',
      representative: '한지훈',
      address: '서울특별시 종로구 종로 14 한국기원회관 빌딩 6층',
      businessType: '서비스업',
      businessItem: '디스플레이 광고',
      defaultMarkupRate: 10,
      paymentDueDays: 60,
      paymentBasis: '월말 마감 익월 60일',
      bankName: '카카오뱅크',
      bankAccountNumber: '3333-12-9876543',
      bankAccountHolder: '한지훈',
      createdAt: now, updatedAt: now,
    },
  ]
}

/**
 * 기존 agencies 와 머지 (id 충돌 시 mock 우선).
 */
export function mergeMockAgencies(existing: Agency[]): Agency[] {
  const mock = generateMockAgencies()
  const map = new Map<string, Agency>()
  for (const a of existing) map.set(a.id, a)
  for (const a of mock) map.set(a.id, a)
  return [...map.values()]
}
